FROM ibmcom/powerai:1.7.0-all-ubuntu18.04-py37
# Copy the Launcher into the environment
COPY app /app
WORKDIR /app

# Set root user
USER root

# Install useful ubuntu packages
RUN apt-get update && \
    apt-get install --no-install-recommends -y gnupg git vim cmake wget unzip

ARG PATH=/opt/anaconda/bin/:$PATH
ENV PATH=/opt/anaconda/bin/:$PATH

# Set shell
SHELL ["/bin/bash", "-c"]

# Configure Conda Channels
RUN /opt/anaconda/bin/conda config --prepend channels \
    https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/
RUN /opt/anaconda/bin/conda config --prepend channels \
    https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda-early-access/
RUN conda config --set channel_priority strict



ibm

# Install base python packages
#RUN /opt/anaconda/bin/conda config --prepend channels \
#https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/

RUN /opt/anaconda/bin/conda install -n wmlce -y pandas nodejs jupyterlab 

RUN /opt/anaconda/bin/conda install -c rapidsai -c nvidia -c conda-forge \
    -c defaults rapids=0.12 python=3.7 cudatoolkit=10.1

ENV NB_PREFIX /
ENV SHELL bash
CMD env PATH=$PATH PYTHONPATH=$PYTHONPATH LD_LIBRARY_PATH=$LD_LIBRARY_PATH jupyter lab --notebook-dir=/home/jovyan --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX}
