FROM ibmcom/powerai:1.7.0-base-ubuntu18.04-py37
 
# Copy the Launcher into the environment
COPY app /app
WORKDIR /app

# Set root user
USER root

# Install useful ubuntu packages
RUN apt-get update && \
    apt-get install --no-install-recommends -y gnupg git vim cmake wget unzip

ARG PATH=/opt/anaconda/bin/:$PATH
ENV PATH=/opt/anaconda/bin/:$PATH

# Set shell
SHELL ["/bin/bash", "-c"]

# Configure Conda Channels
#RUN /opt/anaconda/bin/conda config --prepend channels \
#    https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/
#RUN /opt/anaconda/bin/conda config --prepend channels \
#    https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda-early-access/
#RUN conda config --set channel_priority strict

# Install Rapids.ai
RUN conda install -n wmlce -y pandas nodejs jupyterlab powerai-rapids

CMD ["/bin/bash", "/app/launch_jupyter.sh"]
